//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnel_Travel_Guide.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Karnel_Travel_GuideEntities : DbContext
    {
        public Karnel_Travel_GuideEntities()
            : base("name=Karnel_Travel_GuideEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_admin> tb_admin { get; set; }
        public virtual DbSet<tb_category> tb_category { get; set; }
        public virtual DbSet<tb_feedback> tb_feedback { get; set; }
        public virtual DbSet<tb_hotels> tb_hotels { get; set; }
        public virtual DbSet<tb_orders> tb_orders { get; set; }
        public virtual DbSet<tb_packages> tb_packages { get; set; }
        public virtual DbSet<tb_rating> tb_rating { get; set; }
        public virtual DbSet<tb_resorts> tb_resorts { get; set; }
        public virtual DbSet<tb_restaurant> tb_restaurant { get; set; }
        public virtual DbSet<tb_tour> tb_tour { get; set; }
        public virtual DbSet<tb_transportation> tb_transportation { get; set; }
        public virtual DbSet<tb_user> tb_user { get; set; }
    }
}
