//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnel_Travel_Guide.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class tb_orders
    {
        public int o_id { get; set; }
        public string o_items { get; set; }
        public Nullable<int> o_foreign_key { get; set; }
        public Nullable<System.DateTime> o_date { get; set; }
        public Nullable<int> o_total { get; set; }
        public string o_status { get; set; }
        public string o_payment { get; set; }
        public string o_billing_city { get; set; }
        public string o_billing_name { get; set; }
        public string o_quantity { get; set; }


        public HttpPostedFileBase ImageFile { get; set; }


        public List<int> ProductId0 { get; set; }
        public List<int> ProductId1 { get; set; }
        public List<int> ProductId2 { get; set; }
        public List<int> ProductId3 { get; set; }
        public List<int> ProductId4 { get; set; }
        public List<int> ProductId5 { get; set; }
        public List<int> ProductId6 { get; set; }
    }
}
