//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnel_Travel_Guide.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class tb_packages
    {
        public int pac_id { get; set; }
        public string pac_name { get; set; }
        public string pac_description_1 { get; set; }
        public string pac_images { get; set; }
        public int pac_price { get; set; }
        public string pac_discount { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
