//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnel_Travel_Guide.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class tb_restaurant
    {
        public int rest_id { get; set; }
        public string rest_name { get; set; }
        public string rest_description_1 { get; set; }
        public string rest_images { get; set; }
        public int rest_price { get; set; }
        public Nullable<int> rest_rating { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
