//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnel_Travel_Guide.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class tb_resorts
    {
        public int reso_id { get; set; }
        public string reso_name { get; set; }
        public string reso_description_1 { get; set; }
        public string reso_images { get; set; }
        public int reso_price { get; set; }
        public Nullable<int> reso_rating { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
