//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnel_Travel_Guide.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class tb_transportation
    {
        public int tr_id { get; set; }
        public string tr_name { get; set; }
        public string tr_description { get; set; }
        public string tr_images { get; set; }
        public string tr_discount { get; set; }
        public int tr_price { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
